test: fail if not able to rollout

diff --git a/tests/e2e/env-injection/chainsaw-test.yaml b/tests/e2e/env-injection/chainsaw-test.yaml
--- a/tests/e2e/env-injection/chainsaw-test.yaml
+++ b/tests/e2e/env-injection/chainsaw-test.yaml
@@ -97,7 +97,7 @@ spec:
               sleep 2
               for i in 1 2 3; do
                 kubectl rollout restart deployment && break || sleep 2
-              done
+              done || exit 1 # Exit with error if all attempts fail
 
     - name: 02 - Assert Environment Variables
       try:
