feat: Java workload e2e (#1539)
Co-authored-by: Amir Blum <amirgiraffe@gmail.com>

diff --git a/tests/e2e/workload-lifecycle/chainsaw-test.yaml b/tests/e2e/workload-lifecycle/chainsaw-test.yaml
--- a/tests/e2e/workload-lifecycle/chainsaw-test.yaml
+++ b/tests/e2e/workload-lifecycle/chainsaw-test.yaml
@@ -9,7 +9,7 @@ spec:
   - name: Build and Load Test App Images
     try:
     - script:
-        timeout: 100s
+        timeout: 200s
         content: |
           docker build -t nodejs-unsupported-version:v0.0.1 -f services/nodejs-http-server/unsupported-version.Dockerfile services/nodejs-http-server
           kind load docker-image nodejs-unsupported-version:v0.0.1
@@ -25,6 +25,18 @@ spec:
           kind load docker-image nodejs-manifest-env:v0.0.1
           docker build -t cpp-http-server:v0.0.1 -f services/cpp-http-server/Dockerfile services/cpp-http-server
           kind load docker-image cpp-http-server:v0.0.1
+          docker build -t java-supported-version:v0.0.1 -f services/java-http-server/java-supported-version.Dockerfile services/java-http-server
+          kind load docker-image java-supported-version:v0.0.1
+          docker build -t java-azul:v0.0.1 -f services/java-http-server/java-azul.Dockerfile services/java-http-server
+          kind load docker-image java-azul:v0.0.1
+          docker build -t java-supported-docker-env:v0.0.1 -f services/java-http-server/java-supported-docker-env.Dockerfile services/java-http-server
+          kind load docker-image java-supported-docker-env:v0.0.1
+          docker build -t java-supported-manifest-env:v0.0.1 -f services/java-http-server/java-supported-manifest-env.Dockerfile services/java-http-server
+          kind load docker-image java-supported-manifest-env:v0.0.1
+          docker build -t java-latest-version:v0.0.1 -f services/java-http-server/java-latest-version.Dockerfile services/java-http-server
+          kind load docker-image java-latest-version:v0.0.1
+          docker build -t java-old-version:v0.0.1 -f services/java-http-server/java-old-version.Dockerfile services/java-http-server
+          kind load docker-image java-old-version:v0.0.1
 
   - name: Prepare destination
     try:
@@ -60,16 +72,24 @@ spec:
         file: 01-instrument-ns.yaml
     - assert:
         file: 01-assert-runtime-detected.yaml
+
   - name: '01 Add Destination'
     try:
     - apply:
         file: 01-add-destination.yaml
-    - assert:
-        file: 01-assert-pipeline.yaml
+  - name: Assert Pipeline
+    try:
+      - assert:
+          file: 01-assert-pipeline.yaml
+  - name: Assert instrumented
+    try:
     - assert:
         file: 01-assert-instrumented.yaml
+  - name: Assert workload
+    try:
     - assert:
         file: 01-assert-workloads.yaml
+
   - name: '01 - Generate Traffic'
     # at this point, we know the expected services are instrumented because we asserted the instrumentation instance
     # send traffic to all services to verify they are working as expected and verify traces for instrumented ones
@@ -78,7 +98,21 @@ spec:
         timeout: 60s
         content: |
           set -e
-
+          
+          NAMESPACE="default"
+          DEPLOYMENTS=$(kubectl get deployments -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}')
+          
+          
+          for DEPLOYMENT in $DEPLOYMENTS; do
+          echo "Waiting for deployment $DEPLOYMENT to finish rollout..."
+          kubectl rollout status deployment/$DEPLOYMENT -n $NAMESPACE
+          if [ $? -ne 0 ]; then
+          echo "Deployment $DEPLOYMENT failed to finish rollout."
+          exit 1
+          fi
+          done
+          
+          
           # Apply the job
           kubectl apply -f 01-generate-traffic.yaml
 
@@ -124,6 +158,21 @@ spec:
         timeout: 60s
         content: |
           set -e
+          
+          NAMESPACE="default"
+          DEPLOYMENTS=$(kubectl get deployments -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}')
+          
+          
+          for DEPLOYMENT in $DEPLOYMENTS; do
+          echo "Waiting for deployment $DEPLOYMENT to finish rollout..."
+          kubectl rollout status deployment/$DEPLOYMENT -n $NAMESPACE
+          if [ $? -ne 0 ]; then
+          echo "Deployment $DEPLOYMENT failed to finish rollout."
+          exit 1
+          fi
+          done
+
+
           kubectl apply -f 01-generate-traffic.yaml
           job_name=$(kubectl get -f 01-generate-traffic.yaml -o=jsonpath='{.metadata.name}')
           kubectl wait --for=condition=complete job/$job_name
@@ -143,54 +192,3 @@ spec:
               ../../common/flush_traces.sh
             fi
           done
-
-
-  # - name: Verify Trace - Context Propagation
-  #   try:
-  #   - script:
-  #       content: |
-  #         ../../common/traceql_runner.sh tracesql/context-propagation.yaml
-  #   catch:
-  #   - podLogs:
-  #       name: odiglet
-  #       namespace: odigos-system
-  # - name: Verify Trace - Resource Attributes
-  #   try:
-  #   - script:
-  #       content: |
-  #         ../../common/traceql_runner.sh tracesql/resource-attributes.yaml
-  #   catch:
-  #   - podLogs:
-  #       name: odiglet
-  #       namespace: odigos-system
-  # - name: Verify Trace - Span Attributes
-  #   try:
-  #     - script:
-  #         timeout: 60s
-  #         content: |
-  #           ../../common/traceql_runner.sh tracesql/span-attributes.yaml
-  #   catch:
-  #     - podLogs:
-  #         name: odiglet
-  #         namespace: odigos-system
-
-  # - name: Start Odigos UI in background
-  #   try:
-  #    - script:
-  #       timeout: 60s
-  #       content: |
-  #         ../../common/ui-tests/start_odigos_ui.sh
-
-  # - name: Run Cypress tests should pass
-  #   try:
-  #     - script:
-  #         timeout: 60s
-  #         content: |
-  #           ../../common/ui-tests/run_cypress_tests.sh
-
-  # - name: Stop Odigos UI
-  #   try:
-  #     - script:
-  #         timeout: 60s
-  #         content: |
-  #           ../../common/ui-tests/stop_ui_and_clean.sh
