retry helm install

diff --git a/tests/e2e/helm-chart/chainsaw-test.yaml b/tests/e2e/helm-chart/chainsaw-test.yaml
--- a/tests/e2e/helm-chart/chainsaw-test.yaml
+++ b/tests/e2e/helm-chart/chainsaw-test.yaml
@@ -24,8 +24,12 @@ spec:
     - script:
         # TODO(edenfed): Use the latest version of the chart
         content: |
-          git clone https://github.com/odigos-io/odigos-charts.git /tmp/odigos-charts -b align-with-cli
-          cd /tmp/odigos-charts/charts && helm install odigos ./odigos --create-namespace --namespace odigos-test-ns --set image.tag=e2e-test
+          git clone https://github.com/odigos-io/odigos-charts.git /tmp/odigos-charts -b align-with-cli && cd /tmp/odigos-charts/charts
+          # Retry 3 times to avoid flakiness
+          while ! helm install odigos ./odigos --create-namespace --namespace odigos-test-ns --set image.tag=e2e-test --atomic; do
+            echo "Failed to install Odigos, retrying..."
+            sleep 1
+          done
           kubectl label namespace odigos-test-ns odigos.io/system-object="true"
           rm -rf /tmp/odigos-charts
         timeout: 60s
