Move reusable workflows into actions

diff --git a/tests/chaos/network-latency/leader-election/chainsaw-test.yaml b/tests/chaos/network-latency/leader-election/chainsaw-test.yaml
--- a/tests/chaos/network-latency/leader-election/chainsaw-test.yaml
+++ b/tests/chaos/network-latency/leader-election/chainsaw-test.yaml
@@ -16,31 +16,37 @@ spec:
     - name: Install Odigos
       try:
         - script:
-            timeout: 3m
+            timeout: 5m
             content: |
               # The pwd is the directory of this file, so we have to walk up to the project root to find the helm chart
               P="../../../.."
-              helm upgrade --install odigos $P/helm/odigos --create-namespace --namespace odigos-test --set image.tag=e2e-test --set imagePrefix=registry.odigos.io
+              helm upgrade --install odigos $P/helm/odigos --create-namespace --namespace odigos-test --set image.tag="$COMMIT_HASH" --set imagePrefix=public.ecr.aws/y2v0v6s7
               kubectl label namespace odigos-test odigos.io/system-object="true"
 
     - name: Verify Odigos Installation
       try:
         - script:
-            timeout: 5m
+            timeout: 7m
             content: |
               echo "Starting Odigos version check..."
               export ACTUAL_VERSION=$(../../../../cli/odigos version --cluster)
               echo "Actual Version: $ACTUAL_VERSION"
 
-              if [ "$MODE" = "cross-cloud-tests" ]; then
-                if [ "$ACTUAL_VERSION" != "$COMMIT_HASH" ]; then
-                  echo "Odigos version is not the expected commit hash, got $ACTUAL_VERSION"
-                  exit 1
-                fi
-                kubectl wait --for=condition=ready pods --all -n odigos-test --timeout=40s
+              if [ "$ACTUAL_VERSION" != "$COMMIT_HASH" ]; then
+                echo "Odigos version is not the expected commit hash, got $ACTUAL_VERSION"
+                exit 1
               fi
+
+              kubectl wait --for=condition=ready pods --all -n odigos-test --timeout=3m
+
         - assert:
             file: ../../../common/assert/odigos-installed.yaml
+
+      catch:
+        - script:
+            content: |
+              echo "Failure detected. Printing pods in the odigos-test namespace..."
+              kubectl get pods -n odigos-test -o wide
 
     - name: Update deployment probes
       try:
