ci: publish odiglet base with input version (#796)

diff --git a/.github/workflows/publish-odiglet-base-builder.yaml b/.github/workflows/publish-odiglet-base-builder.yaml
--- a/.github/workflows/publish-odiglet-base-builder.yaml
+++ b/.github/workflows/publish-odiglet-base-builder.yaml
@@ -1,16 +1,11 @@
 name: Publish Odiglet Base Builder
 
 on:
-  push:
-    branches:
-      - main
-    paths:
-      - "odiglet/base.Dockerfile"
-  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
-
-# The `workflow_fispatch` event is useful if you want to update the dependencies used
-# in the Dockerfile, so they are consumed by future odiglet builds.
-# those dependencies are tools like `clang` `llvm` `make` `libbpf-devel` `git`
+  workflow_dispatch: 
+    inputs:
+      image_tag:
+        description: 'The new image tag for the base builder docker image (e.g. v1.0)'
+        required: true
 
 permissions:
   contents: write
@@ -29,6 +24,34 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Validate New Version
+        run: |
+          # Fetch tags from Docker Hub
+          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ env.DOCKERHUB_ORG }}/odiglet-base/tags/" | jq -r '.results[].name' | sort -Vr)
+  
+          # Extract the latest version
+          LATEST_VERSION=$(echo "$TAGS" | head -n 1)
+  
+          # New version from workflow input
+          NEW_VERSION=${{ github.event.inputs.image_tag }}
+  
+          # Parse major and minor from latest and new versions
+          LATEST_MAJOR=$(echo $LATEST_VERSION | cut -d. -f1)
+          LATEST_MINOR=$(echo $LATEST_VERSION | cut -d. -f2)
+          NEW_MAJOR=$(echo $NEW_VERSION | cut -d. -f1)
+          NEW_MINOR=$(echo $NEW_VERSION | cut -d. -f2)
+  
+          # Compare versions
+          if [[ $NEW_MAJOR -eq $((LATEST_MAJOR + 1)) && $NEW_MINOR -eq 0 ]]; then
+            echo "New version is a valid major version increment."
+          elif [[ $NEW_MAJOR -eq $LATEST_MAJOR && $NEW_MINOR -eq $((LATEST_MINOR + 1)) ]]; then
+            echo "New version is a valid minor version increment."
+          else
+            echo "Error: New version $NEW_VERSION does not follow the versioning rules."
+            exit 1
+          fi
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Set up QEMU
@@ -40,4 +63,4 @@ jobs:
           platforms: linux/amd64,linux/arm64
           file: ./odiglet/base.Dockerfile
           push: true
-          tags: ${{ env.DOCKERHUB_ORG }}/odiglet-base:latest
+          tags: ${{ env.DOCKERHUB_ORG }}/odiglet-base:${{ github.event.inputs.image_tag }}
